version: '3.9'

services:
  server:
    build: .
    ports: 
      - '5000:3000'
    networks:
      - 'Network1'
  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'clave' 
      POSTGRES_USER: 'root'
      POSTGRES_DB: 'root'
    networks:
      - 'Network1'
networks:
  Network1:
    drive: 'bridge'

